const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
let browser;
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
 const page=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'});
 const errors=[],external=[],paid=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>{const u=new URL(r.request().url());if(!['127.0.0.1','localhost'].includes(u.hostname)){external.push(u.href);return r.abort();}if(/\/(generate|event-review|evidence-review|brief)$/.test(u.pathname))paid.push(u.href);return r.continue();});
 const base=process.env.THESIS_TEST_URL;
 await page.goto(base+'/?company=aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa&view=idea');
 const panel=page.getByRole('region',{name:'Reviewable suggestions',exact:true});await panel.getByRole('heading',{name:'Make your idea testable',exact:true}).waitFor();
 assert.equal(await panel.getByRole('checkbox').count(),3);for(const c of await panel.getByRole('checkbox').all())assert.equal(await c.isChecked(),false);
 const before=(await(await page.request.get(base+'/api/v1/workspace')).json()).result;
 for(const c of await panel.getByRole('checkbox').all())await c.check();
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1100});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`/private/tmp/thesis-proposals-${width}.png`,fullPage:true});}
 await panel.getByRole('button',{name:'Review 3 selected suggestions',exact:true}).click();
 const modal=page.getByRole('dialog',{name:'Review selected suggestions',exact:true});await modal.waitFor();
 assert.equal(await modal.getByLabel('My reasoning',{exact:true}).inputValue(),'I need completed renewal evidence before concluding that demand is durable.');
 assert.equal(await modal.getByLabel('Report deadline 1',{exact:true}).inputValue(),'');
 assert.match(await panel.innerText(),/Flags a risk when the reported figure is at most your chosen threshold, including equality/);
 assert.equal(await modal.getByLabel('Purpose of condition 1',{exact:true}).inputValue(),'risk');
 assert.equal(await modal.getByLabel('Percent',{exact:true}).inputValue(),'');
 await modal.getByRole('checkbox').check();
 await modal.getByLabel('Percent',{exact:true}).fill('15');
 assert.equal(await modal.getByRole('checkbox').isChecked(),false);
 assert.equal(await modal.getByLabel('Condition',{exact:true}).inputValue(),'<=');
 await modal.getByRole('checkbox').check();await modal.getByRole('button',{name:'Approve monitoring',exact:true}).click();
 await modal.getByRole('alert').waitFor();assert.match(await modal.innerText(),/choose an ordered date window/i);
 await modal.getByLabel('Report window start 1',{exact:true}).fill('2025-01-01');await modal.getByLabel('Report deadline 1',{exact:true}).fill('2026-12-31');
 await modal.getByLabel('My reasoning',{exact:true}).fill('I edited this proposed reasoning and require completed renewal evidence.');
 await modal.getByRole('checkbox').check();await modal.getByRole('button',{name:'Approve monitoring',exact:true}).click();await modal.waitFor({state:'hidden'});
 await page.getByRole('main').getByText('Evidence check needed',{exact:true}).waitFor();
 const after=(await(await page.request.get(base+'/api/v1/workspace')).json()).result;
 assert.equal(after.thesis.revision,2);assert.equal(after.versions[0].events.length,1);assert.equal(after.versions[0].conditions[0].role,'risk');assert.equal(after.versions[0].conditions[0].operator,'<=');assert.equal(Number(after.versions[0].conditions[0].threshold),15);assert.equal(after.versions[0].reasoning,'I edited this proposed reasoning and require completed renewal evidence.');assert.equal(after.versions[1].reasoning,before.versions[0].reasoning);
 assert.ok(after.proposals.every(p=>p.status==='approved'));assert.equal(new Set(after.proposals.map(p=>p.accepted_version_id)).size,1);
 await panel.getByText('Previous suggestions (3)',{exact:true}).click();await panel.getByRole('button',{name:'Open the accepted revision ↗',exact:true}).first().click();
 await page.getByRole('main').getByText('I edited this proposed reasoning and require completed renewal evidence.',{exact:true}).waitFor();
 // A separate company exercises a conflicting edit while the review modal stays open.
 const aurora=after.catalogue.find(c=>c.symbol==='AURQ');
 await page.goto(base+'/?company='+aurora.id+'&view=idea');
 await panel.getByRole('checkbox').first().check();await panel.getByRole('button',{name:'Review 1 selected suggestion',exact:true}).click();await modal.waitFor();
 await modal.getByLabel('My reasoning',{exact:true}).fill('Keep this unsaved edit visible after the conflict.');
 const other=(await(await page.request.get(base+'/api/v1/workspace?instrument_id='+aurora.id)).json()).result;
 const v=other.versions[0];
 const changed=await page.request.post(base+'/api/v1/idea',{headers:{'X-Thesis-Request':'local-ui'},data:{instrument_id:aurora.id,expected_revision:v.revision,question:v.question,reasoning:'Changed in another tab',status:'draft',conditions:[],events:[]}});assert.ok(changed.ok());
 await modal.getByRole('button',{name:'Use suggestions in draft',exact:true}).click();await modal.getByRole('alert').waitFor();assert.match(await modal.innerText(),/stale|changed/i);assert.equal(await modal.getByLabel('My reasoning',{exact:true}).inputValue(),'Keep this unsaved edit visible after the conflict.');assert.equal(await modal.getByRole('button',{name:'Use suggestions in draft',exact:true}).isEnabled(),false);
 const current=(await(await page.request.get(base+'/api/v1/workspace?instrument_id='+aurora.id)).json()).result;assert.equal(current.thesis.revision,2);assert.equal(current.versions[0].reasoning,'Changed in another tab');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(paid,[]);
 console.log('Proposal browser passed: unselected before/after cards, three-change atomic approval including a numerical risk, edited reasoning, required dates, historical revision link, stale conflict preserving input, mobile/desktop and zero automatic paid calls.');await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1);});
