const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
let browser;
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[],external=[],calls=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('request',r=>{if(!r.url().startsWith(process.env.THESIS_TEST_URL)) external.push(r.url());if(r.method()==='POST')calls.push(r.url());});
 await page.goto(process.env.THESIS_TEST_URL);
 await page.locator('.watch-item').filter({hasText:'MSFT'}).click();
 const panel=page.getByRole('region',{name:'News and social sentiment',exact:true});
 const checkbox=panel.getByRole('checkbox',{name:'Also check my approved event conditions',exact:true});
 await checkbox.waitFor();assert.equal(await checkbox.isChecked(),true);
 await panel.getByText('Event checks are paused because the approved revision changed. Review the current conditions before resuming.',{exact:true}).waitFor();
 await panel.getByRole('button',{name:'Use current approved events',exact:true}).click();
 await panel.getByText(/Watching approved event revision 2/).waitFor();
 await Promise.all([page.waitForResponse(r=>r.url().includes('/api/v1/workspace')),checkbox.click()]);
 await page.waitForFunction(()=>!document.querySelector('.event-watch-control input').checked);
 assert.equal(await checkbox.isChecked(),false);
 const data=(await (await page.request.get(process.env.THESIS_TEST_URL+'/api/v1/workspace?instrument_id=c767e09f-35ea-5eaf-a626-ff5d3aa4709b')).json()).result;
 assert.equal(data.news_watch.event_version_id,null);
 const old=data.versions.find(v=>v.revision===1),reused=old.evaluations.find(e=>e.manifest.event_review_reuse);
 assert.ok(reused,'Expected an assessment with exact-input reuse proof');
 await page.getByRole('button',{name:'History',exact:true}).click();
 await page.getByLabel('Record',{exact:true}).selectOption(reused.id);
 const eventPanel=page.getByRole('main').getByRole('region',{name:'Event conditions',exact:true});
 await eventPanel.getByText(/Reused the saved interpretation/).waitFor();
 assert.match(await eventPanel.innerText(),/Report matches your required event/);
 await eventPanel.getByRole('button',{name:'Inspect event source 1 ↗',exact:true}).click();
 await page.getByRole('dialog').waitFor();assert.match(await page.getByRole('dialog').innerText(),/Authored fixture/);
 await page.getByRole('dialog').getByRole('button',{name:/close/i}).click();
 const download=page.waitForEvent('download');
 await page.getByRole('button',{name:'Download research record',exact:true}).click();
 const file=await download;await file.saveAs('/private/tmp/thesis-event-watch-export.html');
 assert.match(require('node:fs').readFileSync('/private/tmp/thesis-event-watch-export.html','utf8'),/reused for identical/);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:960});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow at ${width}`);}
 await page.screenshot({path:'/private/tmp/thesis-event-watch-history.png',fullPage:true});
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.ok(calls.every(u=>u.endsWith('/event-watch')));
 console.log('Event-watch browser passed: changed revision paused, explicit reapproval/stop through real API, exact-input reuse history/source/export, 320/390/1440 layouts; no provider requests.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();});
