const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
let browser;
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
 const page=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'});
 const errors=[],external=[],calls=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>{const u=new URL(r.request().url());if(!['127.0.0.1','localhost'].includes(u.hostname)){external.push(u.href);return r.abort();}if(/\/(sentiment|refresh|generate|brief)$/.test(u.pathname))calls.push(u.href);return r.continue();});
 const base=process.env.THESIS_TEST_URL,iid='c767e09f-35ea-5eaf-a626-ff5d3aa4709b';
 await page.goto(base+'/?company='+iid+'&view=workspace');
 const panel=page.getByRole('region',{name:'News and social sentiment',exact:true});
 await panel.getByRole('button',{name:'Hacker News',exact:true}).click();
 assert.match(await panel.innerText(),/4 relevant of 4 selected comments/);
 await panel.getByText('Sample details & method',{exact:true}).click();
 assert.match(await panel.innerText(),/Tech-community comments, not investor consensus/);
 assert.match(await panel.innerText(),/negative leaning/i);
 assert.equal(await panel.locator('.sentiment-items article').count(),4);
 await panel.getByRole('button',{name:'Original sources',exact:true}).click();
 assert.equal(await panel.getByRole('region',{name:'Original selected sources',exact:true}).locator('article').count(),4);
 assert.match(await panel.innerText(),/Hacker News · comments/);
 assert.doesNotMatch(await panel.getByRole('region',{name:'Original selected sources',exact:true}).innerText(),/Synthetic Microsoft negative opinion/);
 await panel.getByRole('region',{name:'Original selected sources',exact:true}).getByRole('button',{name:'Inspect original source ↗',exact:true}).first().click();
 const modal=page.getByRole('dialog');await modal.waitFor();
 assert.match(await modal.innerText(),/Hacker News · comments/);
 assert.match(await modal.innerText(),/Each sentiment reading identifies any saved parent context it used/);
 assert.match(await modal.getByRole('link',{name:'Read original post ↗',exact:true}).getAttribute('href'),/^https:\/\/news.ycombinator.com\/item\?id=/);
 await page.keyboard.press('Escape');
 await panel.getByRole('button',{name:'Reddit discussion',exact:true}).click();
 assert.equal(await panel.getByRole('region',{name:'Original selected sources',exact:true}).locator('article').count(),4);
 assert.doesNotMatch(await panel.getByRole('region',{name:'Original selected sources',exact:true}).innerText(),/Hacker News · comments/);
 await panel.getByText('Social source coverage',{exact:true}).click();
 assert.match(await panel.innerText(),/13 November 2026/);
 assert.match(await panel.innerText(),/Hacker News comments · enabled · checked/);
 assert.equal(await panel.getByRole('checkbox',{name:'Watch news + social changes',exact:true}).isChecked(),false);
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1100});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`/private/tmp/thesis-social-platforms-${width}.png`,fullPage:true});}
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(calls,[]);
 console.log('Social-platform browser passed: separate selected/ original sources, exact comment links, source coverage, disabled watch, responsive layouts and no provider requests.');
 await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1);});
