const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
let browser,page;
(async()=>{
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 page=await context.newPage();
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.THESIS_TEST_URL+'/?company=aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa&view=workspace');
 await page.getByRole('heading',{name:'Northstar Software',exact:true}).waitFor();
 await page.locator('.watch-item').filter({hasText:'MSFT'}).click();
 await page.getByRole('heading',{name:'Microsoft',exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Refresh filings',exact:true}).isEnabled(),false);
 assert.equal(await page.getByRole('button',{name:'Load next recorded development'}).count(),0);
 assert.equal(await page.getByRole('button',{name:'Select key passages',exact:true}).count(),0);
 assert.doesNotMatch(await page.getByRole('main').innerText(),/Fictional company/);
 await page.getByRole('tab',{name:'Fundamentals',exact:true}).click();
 const trail=page.getByRole('region',{name:'Filing calculation trail'});
 await trail.getByText('Annual',{exact:true}).waitFor();
 await trail.getByText('Operating margin · 23.08%',{exact:true}).click();
 assert.match(await trail.innerText(),/Stored calculation: 23.076923/);
 assert.match(await trail.getByRole('link',{name:'Open original SEC filing ↗'}).getAttribute('href'),/^https:\/\/www.sec.gov\/Archives\/edgar\/data\/789019\//);
 await page.screenshot({path:'/private/tmp/thesis-sec-synthetic-desktop.png',fullPage:true});
 for(const width of [320,390,768,1056]){
   await page.setViewportSize({width,height:960});
   assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`SEC layout overflow ${width}`);
 }
 await page.setViewportSize({width:390,height:900});
 await page.getByRole('button',{name:'Save my reasoning',exact:true}).click();
 await page.getByLabel('My reasoning',{exact:true}).fill('Synthetic test reasoning: growth may persist if operating economics hold up.');
 await page.getByRole('button',{name:'Add condition',exact:true}).click();
 await page.getByLabel('Percent',{exact:true}).last().fill('15');
 assert.equal(await page.getByLabel('Reporting period 1',{exact:true}).inputValue(),'annual');
 await page.getByRole('checkbox').check();
 await page.getByLabel('Reporting period 1',{exact:true}).selectOption('quarter');
 assert.equal(await page.getByRole('checkbox').isChecked(),false);
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Approve monitoring',exact:true}).click();
 await page.getByText('Evidence is incomplete',{exact:true}).waitFor();
 await page.getByText(/No quarter observation: available figures cover a different reporting period type/).waitFor();
 await page.getByRole('button',{name:'Edit idea',exact:true}).click();
 await page.getByLabel('Reporting period 1',{exact:true}).selectOption('annual');
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Approve monitoring',exact:true}).click();
 await page.getByText('All conditions met',{exact:true}).waitFor();
 await page.locator('.idea-panel').getByRole('button',{name:'Source',exact:true}).click();
 await page.getByRole('dialog').getByText('CALCULATED FROM SEC FACTS',{exact:true}).waitFor();
 assert.doesNotMatch(await page.getByRole('dialog').innerText(),/AUTHORED FICTIONAL/);
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'History',exact:true}).click();
 await page.getByLabel('Record',{exact:true}).locator('option').filter({hasText:'Revision 1 ·'}).first().waitFor({state:'attached'});
 const options=await page.getByLabel('Record',{exact:true}).locator('option').allTextContents();
 assert.ok(options.some(v=>v.includes('Revision 1')&&v.includes('Not enough evidence')));
 // A user-defined age limit needs renewed approval and preserves the last figure.
 await page.getByRole('button',{name:'Edit idea',exact:true}).click();
 await page.getByRole('checkbox').check();
 await page.getByLabel('Days since period end 1',{exact:true}).fill('1');
 assert.equal(await page.getByRole('checkbox').isChecked(),false);
 await page.getByText(/Already too old under this limit/).waitFor();
 for(const width of [320,390,768,1440]){
   await page.setViewportSize({width,height:1000});
   assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`age editor overflow ${width}`);
   if(width===390) await page.screenshot({path:"/private/tmp/thesis-age-editor-mobile.png",fullPage:true});
 }
 await page.screenshot({path:'/private/tmp/thesis-age-editor.png',fullPage:true});
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Approve monitoring',exact:true}).click();
 await page.getByText(/Too old to assess/).first().waitFor();
 assert.match(await page.locator('.idea-panel').innerText(),/Last reported · outside your age limit/);
 await page.locator('.idea-panel').getByRole('button',{name:'Source',exact:true}).click();
 await page.getByRole('dialog').getByText('CALCULATED FROM SEC FACTS',{exact:true}).waitFor();
 await page.keyboard.press('Escape');
 // Clock updates remain discoverable while idle and when returning to the app.
 await page.waitForResponse(r=>r.url().includes('/api/v1/workspace'),{timeout:35000});
 await Promise.all([page.waitForResponse(r=>r.url().includes('/api/v1/workspace')),page.evaluate(()=>window.dispatchEvent(new Event('focus')))]);
 await page.screenshot({path:'/private/tmp/thesis-age-expired.png',fullPage:true});
 await page.getByRole('button',{name:'Edit idea',exact:true}).click();
 await page.getByRole('checkbox').check();
 await page.getByLabel('Days since period end 1',{exact:true}).fill('');
 assert.equal(await page.getByRole('checkbox').isChecked(),false);
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Approve monitoring',exact:true}).click();
 await page.getByText('All conditions met',{exact:true}).first().waitFor();
 await page.getByRole('button',{name:'History',exact:true}).click();
 const ageRecord=await page.getByLabel('Record',{exact:true}).locator('option').filter({hasText:'Revision 3 ·'}).last().getAttribute('value');
 await page.getByLabel('Record',{exact:true}).selectOption(ageRecord);
 assert.match(await page.locator('.history-page').innerText(),/Maximum reporting age: 1 day/);
 assert.match(await page.locator('.history-page').innerText(),/Too old to assess/);
 await page.setViewportSize({width:390,height:900});
 // A scope-only edit conflict remains understandable on a narrow display.
 await page.getByRole('button',{name:'Edit idea',exact:true}).click();
 const other=await page.context().newPage();
 await other.goto(page.url());
 await other.getByRole('button',{name:'Edit idea',exact:true}).click();
 await other.getByLabel('Reporting period 1',{exact:true}).selectOption('quarter');
 await other.getByLabel('Days since period end 1',{exact:true}).fill('90');
 await other.getByRole('button',{name:'Save draft',exact:true}).click();
 await other.getByRole('status').filter({hasText:'Draft saved'}).waitFor();
 await page.getByRole('button',{name:'Save draft',exact:true}).click();
 const comparison=page.getByRole('region',{name:'Resolve conflicting edits'});
 await comparison.waitFor();
 assert.match(await comparison.locator('.comparison-columns > div').first().innerText(),/Quarterly/);
 assert.match(await comparison.locator('.comparison-columns > div').last().innerText(),/Annual/);
 assert.match(await comparison.locator('.comparison-columns > div').first().innerText(),/Maximum reporting age: 90 days/);
 assert.match(await comparison.locator('.comparison-columns > div').last().innerText(),/No age limit/);
 await page.getByRole('button',{name:'Use saved version',exact:true}).click();
 await page.getByRole('button',{name:'Save draft',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Draft saved'}).waitFor();
 await other.close();
 // An unsuccessful provider refresh reloads the persisted coverage, never retries HTTP.
 let failed=false,requests=0;
 await page.route('**/api/v1/workspace*',async route=>{
   const response=await route.fetch();const data=await response.json();
   data.result.sec_status.configured=true;
   if(failed){data.result.coverage='stale';data.result.source_checks=data.result.source_checks.map(c=>({...c,state:'denied',outcome:'denied'}));}
   await route.fulfill({response,json:data});
 });
 await page.route('**/api/v1/sec/*/refresh',route=>{failed=true;requests++;return route.fulfill({status:422,json:{result:{errors:[{error_message:'SEC access denied or rate-limited.'}]}}});});
 await page.getByRole('button',{name:'Workspace',exact:true}).click();
 await page.reload();
 await page.getByRole('tab',{name:'Source coverage',exact:true}).click();
 await page.getByRole('button',{name:'Refresh filings',exact:true}).click();
 await page.getByText('Access denied',{exact:true}).waitFor();
 assert.equal(requests,1);
 await page.unroute('**/api/v1/sec/*/refresh');
 await page.unroute('**/api/v1/workspace*');
 await page.getByRole('button',{name:'Add company',exact:true}).filter({visible:true}).click();
 await page.getByRole('dialog').getByLabel('Find a company').fill('AAPL');
 await page.route('**/api/v1/sec/companies',route=>route.fulfill({status:422,json:{result:{errors:[{error_message:'Connection interrupted. Please retry.'}]}}}));
 await page.getByRole('button',{name:/Add AAPL/}).click();
 await page.getByRole('dialog').getByRole('alert').filter({hasText:'Connection interrupted'}).waitFor();
 assert.equal(await page.getByRole('dialog').getByLabel('Find a company').inputValue(),'AAPL');
 await page.unroute('**/api/v1/sec/companies');
 await page.getByRole('button',{name:/Add AAPL/}).click();
 await page.getByRole('heading',{name:'Apple',exact:true}).waitFor();
 await page.getByRole('tab',{name:'Source coverage',exact:true}).click();
 await page.getByText('Not checked',{exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Refresh filings',exact:true}).isEnabled(),false);
 await page.screenshot({path:'/private/tmp/thesis-sec-empty-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('SEC browser passed: synthetic fiscal calculations, source trail, annual-v-quarter approval and history, missing configuration, empty new company, 320–1440px layouts. No live HTTP/provider calls.');
 await browser.close();
})().catch(async e=>{console.error(e);if(page){await page.screenshot({path:'/private/tmp/thesis-sec-browser-failure.png',fullPage:true}).catch(()=>{});console.error(await page.locator('body').innerText().catch(()=>''));}if(browser)await browser.close();process.exit(1);});
