const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
let browser;
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
 const page=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'});
 const errors=[],external=[],paid=[];
 page.on('pageerror',e=>{errors.push(e.message);console.error('Browser error:',e.message);});
 await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='financialmodelingprep.com'&&r.request().resourceType()==='image')return r.fulfill({status:404,body:''});if(!['127.0.0.1','localhost'].includes(u.hostname)){external.push(u.href);return r.abort();}if(/\/(sentiment|refresh|generate|event-review|evidence-review|brief)$/.test(u.pathname))paid.push(u.href);return r.continue();});
 const base=process.env.THESIS_TEST_URL, iid='c767e09f-35ea-5eaf-a626-ff5d3aa4709b';
 await page.goto(base+'/?company='+iid+'&view=workspace');
 await page.getByRole('tab',{name:'News & discussion',exact:true}).click();
 const panel=page.getByRole('region',{name:'News and social sentiment',exact:true});
 await panel.getByRole('heading',{name:'What’s the tone?',exact:true}).waitFor();
 await panel.getByRole('group',{name:'Sentiment source type',exact:true}).getByRole('button',{name:'Company news',exact:true}).click();
 await panel.getByRole('button',{name:'Watch · off',exact:true}).click();
 const settings=page.getByRole('dialog',{name:'News & discussion · watch',exact:true});
 const watch=settings.getByRole('checkbox',{name:'Watch news + social changes',exact:true});
 assert.equal(await watch.isChecked(),false);
 await page.keyboard.press('Escape');
 await panel.locator('.sentiment-items article').filter({hasText:'Repeated coverage of an earlier development'}).getByRole('button',{name:'Inspect evidence',exact:true}).click();
 const story=page.getByRole('dialog',{name:'Story evidence',exact:true});
 await story.locator('.reporting-evidence summary').first().click();
 assert.match(await story.locator('.reporting-evidence[open]').first().innerText(),/Reported effect: adverse/);
 await story.getByText('Repeated coverage · compare reports',{exact:true}).click();
 assert.match(await story.innerText(),/AI comparison: this report appears to repeat the earlier development/);
 assert.doesNotMatch(await story.innerText(),/InventedCounterparty|SecretLocation/);
 assert.match(await story.innerText(),/margins weakened/);
 for (const width of [320,390,1440]) { await page.setViewportSize({width,height:1100}); assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)); await story.locator('.coverage-comparison[open]').screenshot({path:`/private/tmp/thesis-coverage-comparison-${width}.png`}); }
 await story.getByRole('button',{name:'Inspect compared report ↗',exact:true}).click();
 await page.getByRole('dialog',{name:'Source evidence',exact:true}).waitFor();
 assert.match(await page.getByRole('dialog',{name:'Source evidence',exact:true}).innerText(),/margins weakened/);
 await page.keyboard.press('Escape');
 await page.keyboard.press('Escape');
 await panel.getByText('Sample details & method',{exact:true}).click();
 assert.match(await panel.innerText(),/Related news reports count once/);

 await panel.getByRole('button',{name:'Reddit discussion',exact:true}).click();
 assert.match(await panel.innerText(),/negative leaning/i);
 assert.match(await panel.innerText(),/8 relevant of 8 selected posts/);
 assert.match(await panel.innerText(),/1 distinct author represented/);
 await panel.locator('.sentiment-items article').filter({hasText:'Synthetic Microsoft negative opinion 0'}).getByRole('button',{name:'Inspect evidence',exact:true}).click();
 assert.match(await story.innerText(),/View used for this label/);
 assert.match(await story.innerText(),/I now dislike its margins outlook/);
 await story.getByText('Earlier view in the same post',{exact:true}).click();
 assert.match(await story.innerText(),/I used to admire Microsoft/);
 await story.getByText('Why this label · inspect evidence',{exact:true}).first().click();
 await story.getByRole('button',{name:'Open original source ↗',exact:true}).first().click();
 const modal=page.getByRole('dialog',{name:'Source evidence',exact:true});await modal.waitFor();assert.match(await modal.innerText(),/public post|social/i);assert.equal(await modal.getByRole('link',{name:'Read original post ↗',exact:true}).count(),1);
 await page.keyboard.press('Escape');
 await page.keyboard.press('Escape');
 await panel.getByRole('button',{name:'Watch · off',exact:true}).click();
 await watch.click();await settings.getByLabel('Watch frequency').waitFor();await settings.getByLabel('Watch frequency').selectOption('240');
 await page.waitForFunction(()=>document.querySelector('select[aria-label="Watch frequency"]')?.value==='240');
 await watch.click();await settings.getByLabel('Watch frequency').waitFor({state:'hidden'});
 await page.keyboard.press('Escape');
 const state=(await(await page.request.get(base+'/api/v1/workspace?instrument_id='+iid)).json()).result;
 assert.equal(state.news_watch.enabled,false);assert.equal(state.news_watch.interval_minutes,240);
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1100});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`/private/tmp/thesis-sentiment-${width}.png`,fullPage:true});await panel.locator('.sentiment-items article').first().screenshot({path:`/private/tmp/thesis-sentiment-basis-${width}.png`});}
 await page.getByRole('button',{name:'Updates',exact:true}).click();
 const alerts=page.getByRole('region',{name:'Research update inbox',exact:true});
 const expand=async()=>{for(const summary of await alerts.locator('.inbox-record > summary').all()) {if(await summary.evaluate(e=>!e.parentElement.open))await summary.click();}};
 await alerts.locator('.inbox-record').first().waitFor(); await expand();
 await alerts.locator('.sentiment-alert').getByRole('heading',{name:'Sentiment sample changed',exact:true}).waitFor();
 assert.equal(await alerts.locator('.sentiment-alert').count(),2);
 assert.match(await alerts.innerText(),/positive leaning → negative leaning/);
 await alerts.getByText(/^Previous sample ·/).first().click();
 assert.match(await alerts.innerText(),/Synthetic Microsoft positive opinion/);
 await alerts.getByText('Your reasoning when this alert was created · revision 1',{exact:true}).first().click();
 assert.match(await alerts.innerText(),/I want durable margins before relying on growth/);
 await alerts.getByRole('button',{name:'Inspect alert source ↗',exact:true}).first().click();await modal.waitFor();await page.keyboard.press('Escape');
 await alerts.getByRole('button',{name:'Mark reviewed',exact:true}).first().click();await page.waitForFunction(()=>document.querySelectorAll('.sentiment-alert').length===1);
 await expand();await alerts.getByRole('button',{name:'Leave unresolved',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.sentiment-alert').length===0);
 await alerts.getByLabel('Show updates').selectOption('all');await alerts.locator('.inbox-record').first().waitFor();await expand();assert.equal(await alerts.locator('.sentiment-alert').count(),2);
 assert.match(await alerts.innerText(),/Reviewed/);assert.match(await alerts.innerText(),/Left unresolved/);
 await page.screenshot({path:'/private/tmp/thesis-sentiment-alerts.png',fullPage:true});
 await page.reload();await alerts.getByLabel('Show updates').selectOption('all');await alerts.locator('.inbox-record').first().waitFor();await expand();assert.equal(await alerts.locator('.sentiment-alert').count(),2);
 let batchingRun={id:'batch-ui-check',active:true,lookback_days:7,steps:[{key:'analysis',label:'Sentiment analysis',status:'running',message:'1 of 2 batches complete · reading batch 2',batches:{completed:1,total:2,source_counts:[8,4],message:'1 of 2 batches complete · reading batch 2'}}]};
 await page.route('**/api/v1/companies/'+iid+'/loading',r=>r.fulfill({json:{result:batchingRun}}));
 await page.getByRole('button',{name:'Workspace',exact:true}).click();
 await page.getByRole('tab',{name:'News & discussion',exact:true}).click();
 const batchProgress=panel.getByRole('progressbar',{name:'Sentiment batches complete'});
 await batchProgress.waitFor();assert.equal(await batchProgress.getAttribute('aria-valuenow'),'1');
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1100});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await panel.locator('.sentiment-batch-progress').screenshot({path:`/private/tmp/thesis-batch-progress-${width}.png`});}
 batchingRun={...batchingRun,active:false,steps:[{...batchingRun.steps[0],status:'blocked',batches:{...batchingRun.steps[0].batches,message:'Batch 2 could not finish; 1 completed batches are saved.'}}]};
 await panel.getByText(/Refresh & analyse reuses completed batches/).waitFor();
 await page.reload();await page.getByRole('tab',{name:'News & discussion',exact:true}).click();await batchProgress.waitFor();assert.equal(await batchProgress.getAttribute('aria-valuenow'),'1');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(paid,[]);
 console.log('Sentiment browser passed: separate samples, exact social sources, watch controls persisted, two grouped alerts, saved reasoning, immutable review status, reload, phone/desktop, no automatic external/paid requests.');
 await browser.close();
})().catch(async e=>{console.error(e);const page=browser?.contexts()[0]?.pages()[0];if(page){console.error(await page.locator('body').innerText());await page.screenshot({path:'/private/tmp/thesis-sentiment-journey-failure.png'});}if(browser)await browser.close();process.exit(1);});
