const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
let browser;
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
 const page=await browser.newPage({viewport:{width:1440,height:1050},reducedMotion:'reduce'});
 const errors=[],external=[],paid=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>{const u=new URL(r.request().url());if(!['127.0.0.1','localhost'].includes(u.hostname)){external.push(u.href);return r.abort();}if(/\/(sentiment|refresh|generate|event-review|evidence-review|brief|idea-alert-check)$/.test(u.pathname))paid.push(u.href);return r.continue();});
 const base=process.env.THESIS_TEST_URL,iid='c767e09f-35ea-5eaf-a626-ff5d3aa4709b';
 await page.goto(base+'/?view=updates');
 const inbox=page.getByRole('region',{name:'Research update inbox',exact:true});
 await inbox.getByText('Page 1 of 2',{exact:true}).waitFor();
 assert.equal(await page.locator('.company-header').isVisible(),false);
 assert.equal(await page.locator('.idea-panel').isVisible(),false);
 assert.equal(await page.locator('.mobile-company-picker').isVisible(),false);
 assert.equal(await page.getByRole('button',{name:'Refresh market',exact:true}).isVisible(),false);
 const raw=(await(await page.request.get(base+'/api/v1/research-review?days=0&review=pending')).json()).result;
 const rowkeys=()=>inbox.locator('.inbox-record').evaluateAll(rows=>rows.map(r=>r.dataset.kind+':'+r.dataset.recordId));
 assert.deepEqual(await rowkeys(),raw.records.map(r=>r.kind+':'+r.id));
 assert.match(await inbox.getByLabel('Update counts').innerText(),new RegExp(raw.total+' awaiting review'));
 await inbox.getByRole('button',{name:'Next updates',exact:true}).click();await inbox.getByText('Page 2 of 2',{exact:true}).waitFor();
 const second=(await(await page.request.get(base+'/api/v1/research-review?days=0&review=pending&page=1&cutoff='+encodeURIComponent(raw.cutoff))).json()).result;
 assert.deepEqual(await rowkeys(),second.records.map(r=>r.kind+':'+r.id));
 assert.deepEqual(new Set(await inbox.locator('.inbox-record').evaluateAll(rows=>rows.map(r=>r.dataset.kind))),new Set(['condition','idea','company']));
 // Sidebar tickers filter this inbox; the workspace destination must not change.
 const side=page.getByRole('complementary',{name:'Companies',exact:true});
 const selected=async symbol=>side.locator('.watch-item').filter({hasText:symbol});
 await inbox.getByLabel('Show updates').selectOption('all');
 await (await selected('NSTR')).click();
 await page.waitForFunction(()=>document.querySelectorAll('.inbox-record').length===1 && !document.querySelector('.update-inbox [role="status"]')?.textContent.includes('Loading'));
 assert.equal(new URL(page.url()).searchParams.get('view'),'updates');
 assert.equal(await inbox.getByLabel('Inbox company').inputValue(),'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
 assert.equal(await inbox.getByLabel('Show updates').inputValue(),'all');
 assert.equal(await (await selected('NSTR')).getAttribute('aria-pressed'),'true');
 const north=(await(await page.request.get(base+'/api/v1/research-review?days=0&review=all&instrument_id=aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')).json()).result;
 assert.deepEqual(await rowkeys(),north.records.map(r=>r.kind+':'+r.id));
 await side.getByRole('button',{name:'All companies',exact:true}).click();
 await inbox.getByText('Page 1 of 2',{exact:true}).waitFor();
 assert.equal(await inbox.getByLabel('Inbox company').inputValue(),'');
 assert.equal(await inbox.getByLabel('Show updates').inputValue(),'all');
 await inbox.getByLabel('Inbox company').selectOption(iid);
 await page.waitForFunction(()=>document.querySelector('.watch-item[aria-pressed="true"]')?.textContent.includes('MSFT'));
 assert.equal(await (await selected('MSFT')).getAttribute('aria-pressed'),'true');
 const catalogue=(await(await page.request.get(base+'/api/v1/workspace?instrument_id='+iid)).json()).result.catalogue;
 const empty=catalogue.find(c=>c.symbol==='AURQ'); assert.ok(empty);
 await (await selected('AURQ')).click();
 await inbox.getByRole('heading',{name:'No updates in this view',exact:true}).waitFor();
 assert.equal(await inbox.getByLabel('Inbox company').inputValue(),empty.id);
 assert.equal(await inbox.locator('.inbox-record').count(),0);
 assert.equal(new URL(page.url()).searchParams.get('view'),'updates');
 // Restore the original second page for the existing review/source checks.
 await side.getByRole('button',{name:'All companies',exact:true}).click();
 await inbox.getByLabel('Show updates').selectOption('pending');
 await inbox.getByText('Page 1 of 2',{exact:true}).waitFor();
 await inbox.getByRole('button',{name:'Next updates',exact:true}).click();
 await inbox.getByText('Page 2 of 2',{exact:true}).waitFor();
 for(const width of [320,390,1440]){
   await page.setViewportSize({width,height:1050});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);
   await page.screenshot({path:`/private/tmp/thesis-inbox-${width}.png`,fullPage:true});
 }
 const companyRow=inbox.locator('.inbox-record[data-kind="company"]').first();
 await companyRow.locator(':scope > summary').click();
 await companyRow.getByRole('button',{name:'Inspect alert source ↗',exact:true}).first().click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');
 await companyRow.getByRole('button',{name:'Leave unresolved',exact:true}).click();await inbox.getByText('Page 1 of 2',{exact:true}).waitFor();
 await inbox.getByLabel('Show updates',{exact:true}).selectOption('unresolved');await page.waitForFunction(()=>document.querySelectorAll('.inbox-record').length===1);
 await inbox.locator('.inbox-record > summary').click();assert.match(await inbox.innerText(),/Left unresolved/);
 await inbox.getByLabel('Show updates',{exact:true}).selectOption('all');await inbox.getByLabel('Inbox company').selectOption('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
 await page.waitForFunction(()=>document.querySelectorAll('.inbox-record').length===1);
 await inbox.locator('.change-summary').waitFor();assert.equal(await inbox.locator('.change-summary').count(),1);
 await inbox.locator('.change-summary').click();await page.getByText('Research history',{exact:true}).waitFor();assert.ok(new URL(page.url()).searchParams.get('evaluation'));
 await page.getByRole('button',{name:'Updates',exact:true}).click();
 await side.getByRole('button',{name:'All companies',exact:true}).click();
 // A delayed earlier filter response must not replace the latest selection.
 let release;
 const held=new Promise(resolve=>release=resolve);
 await page.route('**/api/v1/research-review?**',async route=>{const u=new URL(route.request().url());if(u.searchParams.get('review')==='reviewed')await held;await route.continue();});
 await inbox.getByLabel('Show updates').selectOption('reviewed');await inbox.getByLabel('Show updates').selectOption('unresolved');release();
 await page.waitForFunction(()=>document.querySelectorAll('.inbox-record').length===1);
 assert.match(await inbox.innerText(),/Left unresolved/);
 await page.unroute('**/api/v1/research-review?**');
 await page.route('**/api/v1/research-review?**',route=>route.fulfill({status:503,json:{error:{message:'Authored inbox outage'}}}));
 await inbox.getByRole('button',{name:'Refresh inbox',exact:true}).click();await inbox.getByRole('button',{name:'Retry inbox',exact:true}).waitFor();assert.equal(await inbox.locator('.inbox-record').count(),0);
 await page.unroute('**/api/v1/research-review?**');await inbox.getByRole('button',{name:'Retry inbox',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.inbox-record').length===1);
 // Withheld API records cannot expose old retained interpretations in previews.
 await page.route('**/api/v1/research-review?**',async route=>{const response=await route.fetch();const body=await response.json();for(const r of body.result.records){r.detail.withheld=true;r.title='RETAINED_SECRET';r.detail.payload={title:'RETAINED_SECRET',reason:'RETAINED_SECRET'};}await route.fulfill({response,json:body});});
 await inbox.getByRole('button',{name:'Refresh inbox',exact:true}).click();await inbox.getByRole('heading',{name:'Source access changed',exact:true}).waitFor();assert.doesNotMatch(await inbox.innerText(),/RETAINED_SECRET/);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(paid,[]);
 console.log('Inbox browser passed: all three types, exact chronological pages/counts, sidebar/dropdown company filters, empty-company view, status preservation, page reset, all-company reset, source inspection, independent acknowledgement, exact assessment links, stale-response/error recovery/withholding, 320/390/1440 layouts; no model/source requests.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();});
