const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');let browser;
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
 const page=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'}),errors=[],external=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>{const u=new URL(r.request().url());if(!['127.0.0.1','localhost'].includes(u.hostname)){external.push(u.href);return r.abort();}return r.continue();});
 // The isolated server has no enabled provider. Enable only the presentation control;
 // actual POSTs hit server cache and therefore cannot call a paid provider.
 await page.route('**/api/v1/model-status',r=>r.fulfill({json:{result:{enabled:true,budget:{unresolved:0,remaining_usd:'10'}}}}));
 const base=process.env.THESIS_TEST_URL,iid='c767e09f-35ea-5eaf-a626-ff5d3aa4709b',question='Does the supplied evidence confirm a Microsoft contract?';
 await page.goto(base+'/?company='+iid+'&view=workspace');
 const panel=page.getByRole('region',{name:'Question-focused research',exact:true});
 await panel.getByRole('button',{name:'Answer this question',exact:true}).waitFor();
 assert.equal(await panel.getByRole('combobox',{name:'Research question',exact:true}).count(),1);
 assert.equal(await panel.getByLabel('Your research question').count(),0);
 await panel.getByRole('button',{name:'Edit question',exact:true}).click();
 const input=panel.getByLabel('Your research question');await input.fill(question);
 assert.equal(await panel.getByRole('combobox',{name:'Research question',exact:true}).count(),0);
 assert.equal(await input.evaluate(e=>e.form.id),'research-question-form');
 await panel.getByRole('button',{name:'Answer this question',exact:true}).click();
 const answer=panel.getByRole('article',{name:'Saved question answer'});await answer.getByRole('heading',{name:question,exact:true}).waitFor();
 assert.match(await answer.innerText(),/Partial answer|PARTIAL ANSWER/);assert.match(await answer.innerText(),/AI reading · News/);assert.doesNotMatch(await answer.locator('.answer-points').innerText(),/AI reading · Social opinions/);assert.match(await answer.innerText(),/has not confirmed|does not confirm/);
 await answer.locator('summary').filter({hasText:'Evidence 1'}).first().click();
 await answer.getByRole('button',{name:'Inspect this source ↗',exact:true}).first().click();
 const modal=page.getByRole('dialog');await modal.waitFor();assert.match(await modal.innerText(),/not confirmed/);await page.keyboard.press('Escape');
 const downloaded=page.waitForEvent('download');await answer.getByRole('link',{name:'Download private answer ↗',exact:true}).click();assert.match((await downloaded).suggestedFilename(),/^fledge-research-/);
 await input.fill('A different unsaved question?');assert.equal(await answer.getByRole('heading',{name:question,exact:true}).count(),1);
 await answer.getByRole('button',{name:/Explore next:/}).click();assert.match(await panel.innerText(),/Follow-up to:/);
 assert.equal(await input.inputValue(),'What company disclosure would establish a signed contract?');
 await panel.getByRole('button',{name:'Answer this question',exact:true}).click();
 await answer.getByRole('heading',{name:'What company disclosure would establish a signed contract?',exact:true}).waitFor();
 await panel.getByText(/^Question history ·/).click();
 await panel.locator('.question-history button').filter({hasText:question}).click();await answer.getByRole('heading',{name:question,exact:true}).waitFor();
 await answer.getByRole('button',{name:'Use this question in idea draft',exact:true}).click();await modal.waitFor();assert.match(await modal.innerText(),/Save draft/);await page.keyboard.press('Escape');
 const state=(await(await page.request.get(base+'/api/v1/workspace?instrument_id='+iid)).json()).result;assert.equal(state.versions.length,0);assert.ok(!state.news_watch?.enabled);
 const contextQuestion='What do these technical users say about Microsoft software?';
 await panel.locator('.question-history button').filter({hasText:contextQuestion}).click();
 await answer.getByRole('heading',{name:contextQuestion,exact:true}).waitFor();
 assert.match(await answer.innerText(),/1 Reddit post · 1 Hacker News comment · 1 saved parent supplied as context/);
 await answer.locator('summary').filter({hasText:'Evidence 1'}).first().click();
 await answer.getByText('Parent context used for this finding',{exact:true}).first().click();
 assert.match(await answer.innerText(),/I think Microsoft software is excellent/);
 assert.match(await answer.innerText(),/not another source or independent confirmation/);
 await answer.getByRole('button',{name:'Inspect this source ↗',exact:true}).first().click();
 await modal.getByText('Saved parent passages supplied to this answer',{exact:true}).click();
 assert.match(await modal.innerText(),/I think Microsoft software is excellent/);
 assert.equal(await modal.getByRole('link',{name:'Open saved parent discussion ↗',exact:true}).getAttribute('href'),'https://news.ycombinator.com/item?id=99');
 await page.keyboard.press('Escape');
 const contextDownload=page.waitForEvent('download');
 await answer.getByRole('link',{name:'Download private answer ↗',exact:true}).click();
 const contextHtml=require('node:fs').readFileSync(await(await contextDownload).path(),'utf8');
 assert.match(contextHtml,/Parent context used for this finding/);assert.match(contextHtml,/https:\/\/news.ycombinator.com\/item\?id=99/);assert.doesNotMatch(contextHtml,/<script/);
 await page.route('**/api/v1/companies/*/questions',r=>r.request().method()==='POST'?r.fulfill({status:409,json:{result:{errors:[{error_message:'Authored temporary failure; input preserved.'}]}}}):r.continue());
 await input.fill('Keep this unsaved question after failure?');await panel.getByRole('button',{name:'Answer this question',exact:true}).click();await panel.getByRole('alert').waitFor();assert.equal(await input.inputValue(),'Keep this unsaved question after failure?');
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1100});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`/private/tmp/thesis-questions-${width}.png`,fullPage:true});}
 await page.reload();await panel.getByText(/^Question history ·/).click();assert.equal(await panel.locator('.question-history li').count(),3);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('Question browser passed: exact cached answer, sources, export, independent draft, follow-up, history, failure-preserved input, reload, 320/390/1440px. No model/source request.');await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1);});
