const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
let browser;
(async () => {
 browser = await chromium.launch({headless: true, executablePath: process.env.CHROMIUM_PATH});
 const page = await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 const errors=[],external=[],paid=[];
 page.on('pageerror', e=>errors.push(e.message));
 await page.route('**/*', route=> {const u=new URL(route.request().url());if(!['127.0.0.1','localhost'].includes(u.hostname)){external.push(u.href);return route.abort();}if(/\/(event-review|evidence-review|brief)$/.test(u.pathname))paid.push(u.href);return route.continue();});
 await page.goto(process.env.THESIS_TEST_URL+'/?company=aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa&view=idea');
 await page.getByRole('button',{name:'Save an idea',exact:true}).click();
 const modal=page.getByRole('dialog');
 await modal.getByLabel('My reasoning').fill('A launch may support this idea, but a plan is not completion.');
 await modal.getByRole('button',{name:'+ Add event condition',exact:true}).click();
 await modal.getByLabel('Event description 1',{exact:true}).fill('Northstar product launch');
 await modal.getByLabel('Event evidence required 1',{exact:true}).fill('A report explicitly confirms general availability, not plans.');
 await modal.getByLabel('Report window start 1',{exact:true}).fill('2025-01-01');
 await modal.getByLabel('Report deadline 1',{exact:true}).fill('2026-12-31');
 const approval=modal.getByRole('checkbox');const save=modal.getByRole('button',{name:/Approve.*monitor/i});
 await approval.check();assert.equal(await save.isEnabled(),true);
 await modal.getByLabel('Event role 1',{exact:true}).click();
 await modal.getByRole('listbox').locator('[data-value="risk"]').click();assert.equal(await approval.isChecked(),false);
 await approval.check();await modal.getByLabel('Event date meaning 1',{exact:true}).selectOption('event_occurrence');assert.equal(await approval.isChecked(),false);
 assert.match(await modal.innerText(),/full day, month and year/);await modal.getByLabel('Event date meaning 1',{exact:true}).selectOption('report_publication');
 await approval.check();
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`/private/tmp/thesis-event-editor-${width}.png`,fullPage:true});}
 await save.click();await modal.waitFor({state:'hidden'});
 const main=page.getByRole('main');await main.getByRole('region',{name:'Event conditions',exact:true}).waitFor();
 assert.match(await main.innerText(),/Risk to watch|RISK TO WATCH/);await main.getByText('Evidence check needed',{exact:true}).waitFor();
 const state=(await(await page.request.get(process.env.THESIS_TEST_URL+'/api/v1/workspace')).json()).result;
 assert.equal(state.versions[0].conditions.length,0);assert.equal(state.versions[0].events.length,1);const original=state.versions[0];
 await main.getByRole('button',{name:'Edit my idea',exact:true}).click();
 assert.equal(await modal.getByLabel('Event description 1',{exact:true}).inputValue(),'Northstar product launch');
 await modal.getByLabel('Event date meaning 1',{exact:true}).selectOption('event_occurrence');
 await modal.getByLabel('Event deadline 1',{exact:true}).fill('2025-01-02');
 await modal.getByRole('checkbox').check();await save.click();await modal.waitFor({state:'hidden'});
 await main.getByText('Deadline passed · unconfirmed',{exact:true}).waitFor();
 assert.match(await main.innerText(),/Event occurrence window/);
 const currentDownload=page.waitForEvent('download');await main.getByRole('button',{name:'Download research record',exact:true}).click();await(await currentDownload).saveAs('/private/tmp/thesis-event-occurrence-browser-export.html');
 const currentHtml=require('node:fs').readFileSync('/private/tmp/thesis-event-occurrence-browser-export.html','utf8');assert.match(currentHtml,/Event happened 2025-01-01 through 2025-01-02/);
 await main.getByRole('button',{name:'Edit my idea',exact:true}).click();assert.equal(await modal.getByLabel('Event date meaning 1',{exact:true}).inputValue(),'event_occurrence');await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'History',exact:true}).click();
 await page.getByLabel('Record',{exact:true}).selectOption(original.evaluations[0].id);
 assert.match(await main.innerText(),/2026-12-31/);assert.doesNotMatch(await main.innerText(),/Deadline passed · unconfirmed/);
 const download=page.waitForEvent('download');await main.getByRole('button',{name:'Download research record',exact:true}).click();
 const file=await download;await file.saveAs('/private/tmp/thesis-event-browser-export.html');
 const fs=require('node:fs');const html=fs.readFileSync('/private/tmp/thesis-event-browser-export.html','utf8');assert.match(html,/Northstar product launch/);assert.match(html,/Event evidence/);assert.match(html,/2026-12-31/);
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`/private/tmp/thesis-event-history-${width}.png`,fullPage:true});}
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(paid,[]);
 console.log('Event approval/date-meaning reset, occurrence editor/export, preserved report-only history, 320/390/1440 layouts and zero automatic paid calls passed.');
 await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1);});
