const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');let browser;
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[],writes=[],external=[];
 page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{const u=new URL(r.request().url());if(!['127.0.0.1','localhost'].includes(u.hostname)){external.push(u.href);return r.abort();}if(r.request().method()!=='GET')writes.push(u.pathname);return r.continue();});
 const base=process.env.THESIS_TEST_URL,iid='c767e09f-35ea-5eaf-a626-ff5d3aa4709b';
 await page.goto(base+'/?company='+iid+'&view=workspace');await page.getByText('Watch check history',{exact:true}).click();
 const history=page.locator('.watch-check-history');await history.getByRole('article',{name:'Scheduled watch check'}).first().waitFor();
 assert.equal(await history.getByRole('article',{name:'Scheduled watch check'}).count(),6);
 assert.match(await history.innerText(),/Completion missing/);assert.match(await history.innerText(),/Check failed/);assert.match(await history.innerText(),/first source sample established a baseline/);assert.match(await history.innerText(),/1 grouped update created/);assert.match(await history.innerText(),/coverage was incomplete/);
 await history.getByText('What was checked',{exact:true}).nth(3).click();assert.match(await history.innerText(),/r\/stocks: last check failed/);
 await history.getByText('What was checked',{exact:true}).first().click();
 const contextCheck=history.getByLabel('Original reply context check');
 assert.match(await contextCheck.innerText(),/2 original API requests/);
 assert.match(await contextCheck.innerText(),/1 parents used by the saved analysis/);
 assert.equal(await page.getByRole('checkbox',{name:'Watch news + social changes',exact:true}).isChecked(),false);
 await page.locator('.watch-options').waitFor({state:'detached'});
 assert.equal(await page.locator('.watch-options').count(),0);
 assert.equal(await page.locator('.private-check-options').count(),0);
 const watchBox=page.getByRole('checkbox',{name:'Watch news + social changes',exact:true});
 const contextBox=page.getByRole('checkbox',{name:'Check original reply context during watches',exact:true});
 await watchBox.click();await page.getByRole('combobox',{name:'Watch frequency',exact:true}).waitFor();
 await page.getByText('Watch settings',{exact:true}).click();
 await page.getByText('Automatic event checks · off',{exact:true}).click();
 assert.equal(await page.getByRole('checkbox',{name:'Also check my approved event conditions',exact:true}).isDisabled(),true);
 await page.getByText('Original reply context · off',{exact:true}).click();
 assert.equal(await contextBox.isChecked(),false);assert.equal(await contextBox.isDisabled(),false);
 await contextBox.click();
 await page.getByText('Original reply context · on',{exact:true}).waitFor();
 await Promise.all([page.waitForResponse(r=>r.url().endsWith('/news-watch')&&r.request().method()==='POST'&&r.status()===200),page.getByRole('combobox',{name:'Watch frequency',exact:true}).selectOption('240')]);
 await page.reload();await page.getByText('Watch settings',{exact:true}).click();await page.getByText('Original reply context · on',{exact:true}).click();
 assert.equal(await contextBox.isChecked(),true);
 assert.equal(await page.getByRole('combobox',{name:'Watch frequency',exact:true}).inputValue(),'240');
 await watchBox.click();
 await page.locator('.watch-options').waitFor({state:'detached'});
 assert.equal(await page.locator('.watch-options').count(),0);
 assert.equal(await page.locator('.private-check-options').count(),0);
 await watchBox.click();await page.getByText('Watch settings',{exact:true}).click();
 await page.getByText('Original reply context · on',{exact:true}).click();
 assert.equal(await contextBox.isChecked(),true);
 await contextBox.click();await page.getByText('Original reply context · off',{exact:true}).waitFor();
 await watchBox.click();
 await page.locator('.watch-options').waitFor({state:'detached'});
 assert.equal(await watchBox.isChecked(),false);
 await page.getByText('Watch check history',{exact:true}).click();
 await history.getByText('What was checked',{exact:true}).first().click();
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`/private/tmp/thesis-watch-history-${width}.png`,fullPage:true});}
 await history.getByRole('link',{name:'Review created updates ↗',exact:true}).click();
 const inbox=page.getByRole('region',{name:'Research update inbox',exact:true});
 await inbox.getByRole('heading',{name:'New adverse or mixed company reporting',exact:true}).waitFor();
 assert.match(await inbox.innerText(),/New adverse or mixed company reporting/);
 assert.deepEqual(errors,[]);console.log('Browser writes:',JSON.stringify(writes));assert.equal(writes.filter(p=>p.endsWith('/news-watch')).length,7);assert.ok(writes.every(p=>p.endsWith('/news-watch')||p.endsWith('/loading')));assert.deepEqual(external,[]);console.log('Watch history browser passed: six recorded outcomes, bounded context history, explicit opt-in, frequency persistence, stop/opt-out, source detail, update link, 320/390/1440px. No browser request directly submits model analysis or source refresh; first-open loading requests remain allowed.');await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1);});
