const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');let browser;
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
 const page=await browser.newPage({viewport:{width:1440,height:1050},reducedMotion:'reduce'});
 const errors=[],external=[],paid=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>{const u=new URL(r.request().url());if(!['127.0.0.1','localhost'].includes(u.hostname)){external.push(u.href);return r.abort();}if(/\/(sentiment|refresh|generate|event-review|evidence-review|brief|idea-alert-check)$/.test(u.pathname))paid.push(u.href);return r.continue();});
 const base=process.env.THESIS_TEST_URL,iid='c767e09f-35ea-5eaf-a626-ff5d3aa4709b';
 await page.goto(base+'/?company='+iid+'&view=updates');
 await page.getByRole('button',{name:'Open weekly review ↗',exact:true}).click();
 const region=page.getByRole('region',{name:'Periodic research review',exact:true});
 const schedule=region.getByRole('region',{name:'Scheduled weekly reviews',exact:true});
 await schedule.getByRole('button',{name:'Open saved review',exact:true}).first().waitFor();
 const before=(await(await page.request.get(base+'/api/v1/research-review')).json()).result;
 const history=(await(await page.request.get(base+'/api/v1/scheduled-reviews')).json()).result;
 assert.equal(history.items.length,2);assert.equal(history.settings.enabled,false);
 assert.equal(history.items[0].total,0);assert.ok(history.items[1].total>0);
 await schedule.getByText('Weekly review settings',{exact:true}).click();
 await schedule.getByLabel('Enable weekly reviews',{exact:true}).check();
 await schedule.getByLabel('Weekly review day',{exact:true}).selectOption('1');
 await schedule.getByLabel('Weekly review time',{exact:true}).fill('08:30');
 await schedule.getByLabel('Weekly review time zone',{exact:true}).fill('Asia/Singapore');
 await schedule.getByRole('button',{name:'Save weekly schedule',exact:true}).click();
 await schedule.getByText('Weekly review schedule saved.',{exact:true}).waitFor();
 let settings=(await(await page.request.get(base+'/api/v1/scheduled-reviews')).json()).result.settings;
 assert.equal(settings.enabled,true);assert.equal(settings.minute_of_day,510);assert.equal(settings.weekday,1);
 await page.reload();await schedule.getByText('Weekly review settings',{exact:true}).click();
 assert.equal(await schedule.getByLabel('Weekly review time',{exact:true}).inputValue(),'08:30');
 await schedule.getByLabel('Enable weekly reviews',{exact:true}).uncheck();
 await schedule.getByRole('button',{name:'Save weekly schedule',exact:true}).click();
 await schedule.getByText('Weekly reviews are off. Saved reviews remain available.',{exact:true}).waitFor();
 await schedule.getByRole('button',{name:'Open saved review',exact:true}).first().click();
 await region.getByText('Back to current review',{exact:true}).waitFor();
 await region.getByText('No saved updates match this view. Check coverage above; this does not establish that nothing important happened.',{exact:true}).waitFor();
 assert.match(await region.innerText(),/unreviewed updates were recorded before this period/);
 await schedule.getByRole('button',{name:'Open saved review',exact:true}).nth(1).click();
 await region.getByText('Inspect this reasoning check',{exact:true}).first().waitFor();
 const url=page.url();assert.equal(new URL(url).searchParams.get('review_id'),history.items[1].id);
 await page.reload();await region.getByText('Inspect this reasoning check',{exact:true}).first().click();
 const check=region.getByRole('region',{name:'Evidence linked to saved reasoning',exact:true}).first();
 assert.equal(await check.getByRole('button',{name:'Mark idea alert reviewed',exact:true}).count(),0);
 assert.equal(await check.getByRole('button',{name:'Leave idea alert unresolved',exact:true}).count(),0);
 await check.getByText('Inspect the source evidence',{exact:true}).first().click();
 await check.getByRole('button',{name:'Open cited source ↗',exact:true}).first().click();
 await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');
 const downloadEvent=page.waitForEvent('download');await region.getByRole('link',{name:'Download this review',exact:true}).click();
 const download=await downloadEvent,html=fs.readFileSync(await download.path(),'utf8');
 assert.match(html,/Saved membership/);assert.match(html,/Source access checked/);assert.doesNotMatch(html,/<script/);
 assert.equal((html.match(/<section>/g)||[]).length,history.items[1].total);
 await schedule.getByRole('button',{name:'Mark review seen',exact:true}).nth(1).click();
 await schedule.getByText('Review marked seen. Individual alerts are unchanged.',{exact:true}).waitFor();
 const after=(await(await page.request.get(base+'/api/v1/research-review')).json()).result;
 assert.deepEqual(after.records.map(r=>[r.id,r.review_action]),before.records.map(r=>[r.id,r.review_action]));
 assert.deepEqual(after.totals,before.totals);
 settings=(await(await page.request.get(base+'/api/v1/scheduled-reviews')).json()).result.settings;
 assert.equal(settings.unseen_count,1);assert.equal(settings.enabled,false);
 await schedule.getByText('Weekly review settings',{exact:true}).click();
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1050});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow at ${width}`);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`/private/tmp/thesis-scheduled-review-${width}.png`,fullPage:true});}
 await page.setViewportSize({width:390,height:1050});await page.screenshot({path:'/private/tmp/thesis-scheduled-review-controls-390.png'});
 await region.getByRole('button',{name:'Back to current review',exact:true}).click();
 await region.getByLabel('Review company',{exact:true}).waitFor();assert.equal(new URL(page.url()).searchParams.has('review_id'),false);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(paid,[]);
 console.log('Scheduled review browser passed: schedule save/stop/reload, quiet-week coverage, frozen membership, original sources, private export, deep link, seen independent of alerts, 320/390/1440 layouts; no external/model requests.');await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1);});
