const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
let browser;
(async () => {
  browser = await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[],external=[],blockedLogos=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*', route => {
    const r=route.request(),u=new URL(r.url());
    if(u.origin===new URL(process.env.THESIS_TEST_URL).origin)return route.continue();
    if(u.hostname==='financialmodelingprep.com'&&r.resourceType()==='image'){blockedLogos.push(r.url());return route.fulfill({status:404,body:'Authored unavailable logo'});}
    external.push(r.url());return route.abort();
  });
  await page.goto(process.env.THESIS_TEST_URL);
  await page.locator('.watch-item').filter({hasText:'MSFT'}).click();
  await page.getByRole('tab',{name:'Compare & value',exact:true}).click();
  const panel=page.getByRole('region',{name:'Valuation scenarios',exact:true});
  await panel.getByText('Explore the assumptions',{exact:true}).waitFor();
  const targets=page.getByRole('region',{name:'Analyst price targets',exact:true});
  await targets.getByText('USD 125.50',{exact:true}).first().waitFor();
  assert.match(await targets.innerText(),/12 analysts in the reported poll/);
  // Failed refresh never clears a retained snapshot or changes scenario inputs.
  await page.route('**/analyst-targets/refresh',async r=>{
    await new Promise(resolve=>setTimeout(resolve,300));
    await r.fulfill({status:503,json:{result:{errors:[{error_message:'Authored source outage; saved targets retained.'}]}}});
  });
  await targets.getByRole('button',{name:'Refresh analyst targets',exact:true}).click();
  await targets.getByRole('status').waitFor();
  assert.ok(await targets.getByText('USD 125.50',{exact:true}).first().isVisible());
  await targets.getByRole('alert').filter({hasText:'Authored source outage'}).waitFor();
  assert.ok(await targets.getByText('USD 125.50',{exact:true}).first().isVisible());
  await page.unroute('**/analyst-targets/refresh');
  assert.equal(await panel.locator('form').isVisible(), false);
  await panel.getByRole('button',{name:'Build a scenario',exact:true}).click();
  await panel.getByText('Compare reference multiples',{exact:true}).click();
  await panel.getByText(/P\/E 28.5/).first().waitFor();
  await page.getByLabel('Valuation title',{exact:true}).fill('Authored two-case comparison');
  await page.getByLabel('Valuation horizon',{exact:true}).selectOption('2');
  await page.getByLabel('Case 1 growth',{exact:true}).fill('10');
  await page.getByLabel('Case 1 margin',{exact:true}).fill('20');
  const option=await page.getByLabel('Case 1 reference',{exact:true}).locator('option').filter({hasText:'AAPL'}).getAttribute('value');
  await page.getByLabel('Case 1 reference',{exact:true}).selectOption(option);
  assert.equal(await page.getByLabel('Case 1 multiple',{exact:true}).inputValue(),'28.5');
  await page.getByLabel('Case 1 multiple',{exact:true}).fill('25');
  assert.equal(await page.getByLabel('Case 1 reference',{exact:true}).inputValue(),'');
  await page.getByLabel('Case 1 rationale',{exact:true}).fill('Authored sensitivity assumptions; not an actual forecast.');
  await page.getByRole('button',{name:'Add case',exact:true}).click();
  await page.getByLabel('Case 2 growth',{exact:true}).fill('10');
  await page.getByLabel('Case 2 margin',{exact:true}).fill('-5');
  await page.getByLabel('Case 2 multiple',{exact:true}).fill('25');
  await page.getByLabel('Case 2 rationale',{exact:true}).fill('Authored loss case should give no positive P/E value.');
  await page.getByRole('button',{name:'Calculate scenarios',exact:true}).click();
  const results=page.getByRole('region',{name:'Valuation results',exact:true});
  await results.getByText('USD 3,025bn',{exact:true}).waitFor();
  assert.match(await results.innerText(),/Positive projected earnings are required/);
  await results.getByText('Inputs, calculation and sensitivity',{exact:true}).first().click();
  assert.match(await results.innerText(),/Exact equity result: 3025000000000 USD/);
  await page.getByRole('button',{name:'Save this comparison',exact:true}).click();
  await results.getByText('Saved record',{exact:true}).waitFor();
  await page.waitForFunction(()=>{const s=document.querySelector('select[aria-label="Saved valuation comparison"]');return s && !s.disabled && !!s.value;});
  const savedId=await page.getByLabel('Saved valuation comparison',{exact:true}).inputValue();
  const download=await (await results.getByRole('link',{name:'Download this scenario'})).getAttribute('href');
  const response=await page.request.get(process.env.THESIS_TEST_URL+download);const html=await response.text();
  assert.match(html,/3025000000000/);assert.match(html,/default-src 'none'/);assert.doesNotMatch(html,/<script/);
  await page.screenshot({path:'/private/tmp/thesis-valuation-1440.png',fullPage:true});
  for(const width of [320,390,768]){await page.setViewportSize({width,height:960});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Valuation overflow ${width}`);}
  await page.setViewportSize({width:390,height:900});await page.screenshot({path:'/private/tmp/thesis-valuation-390.png',fullPage:true});
  await page.reload();await page.getByRole('tab',{name:'Compare & value',exact:true}).click();await page.getByLabel('Saved valuation comparison',{exact:true}).selectOption(savedId);
  await results.getByText('USD 3,025bn',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Use these assumptions in a new comparison',exact:true}).click();
  await page.getByLabel('Valuation method',{exact:true}).selectOption('sales');
  for(const i of [1,2]){await page.getByLabel(`Case ${i} multiple`,{exact:true}).fill('4');}
  await page.getByRole('button',{name:'Calculate scenarios',exact:true}).click();
  await results.getByText('USD 2,420bn',{exact:true}).first().waitFor();
  // A failed save keeps the assumptions and unsaved calculation available.
  await page.route('**/api/v1/valuation/save',r=>r.fulfill({status:409,json:{result:{errors:[{error_message:'Financial data changed. Review the latest annual base.'}]}}}));
  await page.getByRole('button',{name:'Save this comparison',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Financial data changed'}).waitFor();
  assert.equal(await page.getByLabel('Case 1 growth',{exact:true}).inputValue(),'10');
  assert.match(await results.innerText(),/Unsaved calculation/i);
  await page.unroute('**/api/v1/valuation/save');
  // Explicit share prices reuse the same saved financial base and private scenario.
  await page.setViewportSize({width:1440,height:1000});
  await page.getByLabel('Valuation method',{exact:true}).selectOption('earnings');
  for(const i of [1,2])await page.getByLabel(`Case ${i} multiple`,{exact:true}).fill('25');
  await page.getByLabel('Add entry and horizon price references',{exact:true}).check();
  await page.getByLabel('Projected diluted shares in millions',{exact:true}).fill('10000');
  await page.getByLabel('Annual return assumption',{exact:true}).fill('10');
  await page.getByLabel('Price reference valuation date',{exact:true}).fill('2026-09-30');
  await page.getByLabel('Share count basis',{exact:true}).fill('Authored 10 billion economically equivalent common shares; no additional dilution or split assumed.');
  await page.getByRole('button',{name:'Calculate scenarios',exact:true}).click();
  await results.locator('.price-reference-values').getByText('USD 302.50',{exact:true}).waitFor();
  assert.match(await results.innerText(),/Entry reference.*10% return/);
  assert.match(await results.innerText(),/USD 275\.02/);
  assert.match(await results.innerText(),/Positive projected earnings are required/);
  await page.getByRole('button',{name:'Save this comparison',exact:true}).click();
  await results.getByText('Saved record',{exact:true}).waitFor();
  await page.waitForFunction(()=>{const s=document.querySelector('select[aria-label="Saved valuation comparison"]');return s && !s.disabled && !!s.value;});
  const pricedId=await page.getByLabel('Saved valuation comparison',{exact:true}).inputValue();
  const pricedExport=await page.request.get(process.env.THESIS_TEST_URL+await results.getByRole('link',{name:'Download this scenario'}).getAttribute('href'));
  const pricedHtml=await pricedExport.text();
  assert.match(pricedHtml,/Scenario horizon price/);assert.match(pricedHtml,/Entry reference/);assert.match(pricedHtml,/302.5/);
  assert.doesNotMatch(pricedHtml,/<script/);
  await page.screenshot({path:'/private/tmp/thesis-price-reference-desktop.png',fullPage:true});
  for(const width of [320,390,768]){await page.setViewportSize({width,height:960});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Price reference overflow ${width}`);}
  await page.setViewportSize({width:390,height:900});
  await page.screenshot({path:'/private/tmp/thesis-price-reference-phone.png',fullPage:true});
  await page.reload();await page.getByRole('tab',{name:'Compare & value',exact:true}).click();
  await page.getByLabel('Saved valuation comparison',{exact:true}).selectOption(pricedId);
  await results.locator('.price-reference-values').getByText('USD 302.50',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Use these assumptions in a new comparison',exact:true}).click();
  assert.equal(await page.getByLabel('Projected diluted shares in millions',{exact:true}).inputValue(),'10000');
  assert.equal(await page.getByLabel('Price reference valuation date',{exact:true}).inputValue(),'2026-09-30');
  await page.getByLabel('Projected diluted shares in millions',{exact:true}).fill('20000');
  await page.getByRole('button',{name:'Calculate scenarios',exact:true}).click();
  await results.locator('.price-reference-values').getByText('USD 151.25',{exact:true}).waitFor();
  await page.getByLabel('Valuation horizon',{exact:true}).selectOption('1');
  await page.getByRole('button',{name:'Calculate scenarios',exact:true}).click();
  await results.getByText(/scenario horizon has already ended/).first().waitFor();
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  console.log('Valuation browser passed: reference adoption and editing, two cases/loss abstention, exact math, sensitivity, private save/export/reopen/copy, sales method, retained input after conflict and 320–1440 layouts. Plus per-share horizon/entry prices, zero/negative-case abstention, private save/export/reopen/copy, dilution scaling, elapsed horizons and mobile layouts. No external/model requests.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();});
