const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');let browser;
(async()=>{
 browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],external=[],calls=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')calls.push(new URL(r.url()).pathname);});
 await page.route('**/*',r=>{const u=new URL(r.request().url());if(!['127.0.0.1','localhost'].includes(u.hostname)){external.push(u.href);return r.abort();}return r.continue();});
 const base=process.env.THESIS_TEST_URL,iid='c767e09f-35ea-5eaf-a626-ff5d3aa4709b';
 await page.goto(base+'/?company='+iid+'&view=workspace');
 const panel=page.getByRole('region',{name:'News and social sentiment',exact:true});
 await panel.getByRole('button',{name:'Hacker News',exact:true}).click();
 assert.match(await panel.innerText(),/4 saved parent messages supplied as context/);
 const firstCard=panel.locator('.sentiment-items article').first();
 await panel.getByText('Why this label · inspect evidence',{exact:true}).first().click();
 await panel.getByText('Parent context used for this label',{exact:true}).first().click();
 assert.match(await panel.innerText(),/Separate message · not another sentiment vote/);
 assert.match(await panel.innerText(),/I think Microsoft pricing is fair/);
 await panel.getByText('Read the saved parent text',{exact:true}).first().click();
 assert.equal(await panel.getByRole('link',{name:'Open cited parent discussion ↗',exact:true}).first().getAttribute('href'),'https://news.ycombinator.com/item?id=999');
 await panel.getByRole('button',{name:'Original sources',exact:true}).click();
 await panel.getByRole('button',{name:'Inspect original source ↗',exact:true}).first().click();
 const modal=page.getByRole('dialog'),context=modal.getByRole('region',{name:'Original conversation context',exact:true});
 await context.getByText('Parent comment · separate message',{exact:true}).waitFor();
 assert.match(await modal.innerText(),/Microsoft software frustrates me/);
 assert.match(await context.innerText(),/I think Microsoft pricing is fair/);
 assert.match(await context.innerText(),/Loading it does not change a saved label/);
 assert.equal(await context.getByRole('button',{name:'Check original conversation again'}).isDisabled(),true);
 assert.equal(await context.getByRole('link',{name:'Open parent discussion ↗',exact:true}).getAttribute('href'),'https://news.ycombinator.com/item?id=999');
 assert.deepEqual(calls,[]);
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`/private/tmp/thesis-conversation-${width}.png`,fullPage:true});}
 // Frontend acquisition failure is mocked; collector transport is separately exercised in backend tests.
 await page.keyboard.press('Escape');
 let saved;
 await page.route('**/api/v1/social-sources/*/conversation',async route=>{
   if(route.request().method()==='POST')return route.fulfill({status:503,json:{result:{errors:[{error_message:'Authored conversation outage'}]}}});
   const response=await route.fetch();const body=await response.json();saved=body.result;body.result.next_check_at=null;return route.fulfill({response,json:body});
 });
 await panel.getByRole('button',{name:'Inspect original source ↗',exact:true}).first().click();
 await context.getByRole('button',{name:'Check original conversation again'}).click();
 await context.getByRole('alert').waitFor();assert.match(await context.innerText(),/Authored conversation outage/);
 assert.doesNotMatch(await context.innerText(),/I think Microsoft pricing is fair/);
 await page.unroute('**/api/v1/social-sources/*/conversation');
 await page.route('**/api/v1/social-sources/*/conversation',route=>route.request().method()==='POST'?route.fulfill({json:{result:saved}}):route.continue());
 await context.getByRole('button',{name:'Load original conversation',exact:true}).click();
 await context.getByText('Parent comment · separate message',{exact:true}).waitFor();
 await page.keyboard.press('Escape');
 assert.equal(await panel.getByRole('checkbox',{name:'Watch news + social changes',exact:true}).isChecked(),false);
 await page.getByRole('button',{name:'Updates',exact:true}).click();
 const inbox=page.getByRole('region',{name:'Research update inbox',exact:true});
 await inbox.locator('.inbox-record').first().waitFor();
 for(const summary of await inbox.locator('.inbox-record > summary').all()) await summary.click();
 const privateCard=inbox.locator('.idea-alert-card');
 await privateCard.waitFor();
 assert.match(await privateCard.innerText(),/4 saved parent messages were supplied as context/);
 const more=privateCard.locator('summary').filter({hasText:/Inspect \d+ more source connections/});
 if(await more.count()) await more.click();
 const connection=privateCard.locator('.idea-match').filter({has:page.locator('.conversation-context')}).first();
 await connection.getByText('Inspect the source evidence',{exact:true}).click();
 await connection.getByText('Parent context used for this connection',{exact:true}).click();
 assert.match(await connection.innerText(),/Microsoft software frustrates me/);
 assert.match(await connection.innerText(),/I think Microsoft pricing is fair/);
 assert.match(await connection.innerText(),/not a separate source connection/);
 const downloadWait=page.waitForEvent('download');
 await privateCard.getByRole('link',{name:'Download this check',exact:true}).click();
 const download=await downloadWait;
 const html=require('node:fs').readFileSync(await download.path(),'utf8');
 assert.match(html,/Parent context used for this connection/);
 assert.match(html,/I think Microsoft pricing is fair/);
 assert.match(html,/https:\/\/news.ycombinator.com\/item\?id=999/);
 for(const width of [320,390,1440]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`/private/tmp/thesis-private-context-${width}.png`,fullPage:true});}
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(calls.length,2);assert.ok(calls.every(s=>s.endsWith('/conversation')));
 console.log('Conversation browser passed: original reply/parent attribution, private alert context and download, cached read without requests, explicit mocked acquisition/failure recovery, source links, disabled watch, 320/390/1440px. No source/model network requests.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();});
