"""Versioned, code-computed research statements from the existing SEC bundle.

This is a display/research contract, separate from the two monitoring metrics.
No network/model request or annual-minus-YTD inference occurs here.
"""

import hashlib
import json
from datetime import date
from decimal import Decimal, localcontext
from uuid import NAMESPACE_URL, uuid5
from psycopg.types.json import Jsonb
from thesis.db import one
from .normalize import REVENUE, filing_rows, normalize

METHOD = "sec-performance-1"
DEFINITIONS = {
    "revenue": (
        "Revenue",
        "Business performance",
        REVENUE,
        "Sales reported for this period.",
    ),
    "operating_income": (
        "Operating income",
        "Business performance",
        ("OperatingIncomeLoss",),
        "Income from operations before non-operating items and tax.",
    ),
    "net_income": (
        "Net income",
        "Business performance",
        ("NetIncomeLoss",),
        "Reported net income or loss; not a cash-flow measure.",
    ),
    "operating_cash": (
        "Operating cash flow",
        "Cash generation",
        ("NetCashProvidedByUsedInOperatingActivities",),
        "Cash generated by or used in operating activities.",
    ),
    "capital_spending": (
        "Cash capital spending",
        "Cash generation",
        ("PaymentsToAcquirePropertyPlantAndEquipment",),
        "Cash payments for property, plant and equipment; excludes noncash additions.",
    ),
    "cash": (
        "Cash and cash equivalents",
        "Balance sheet",
        ("CashAndCashEquivalentsAtCarryingValue",),
        "Cash and cash equivalents at period end; excludes investments and restricted cash.",
    ),
    "debt_noncurrent": (
        "Long-term debt: noncurrent",
        "Balance sheet",
        ("LongTermDebtNoncurrent",),
        "The reported noncurrent debt component; not total obligations.",
    ),
    "debt_current": (
        "Long-term debt: current portion",
        "Balance sheet",
        ("LongTermDebtCurrent",),
        "The reported current portion of long-term debt; other short-term borrowings may exist.",
    ),
    "commercial_paper": (
        "Commercial paper",
        "Balance sheet",
        ("CommercialPaper",),
        "Separately reported short-term borrowing. Missing data does not mean zero.",
    ),
    "assets": (
        "Total assets",
        "Balance sheet",
        ("Assets",),
        "Reported assets at period end.",
    ),
    "liabilities": (
        "Total liabilities",
        "Balance sheet",
        ("Liabilities",),
        "Includes obligations beyond borrowing; not interchangeable with debt.",
    ),
}


def decimal_text(value):
    number = Decimal(str(value))
    if (
        not number.is_finite()
        or abs(number.adjusted()) > 100
        or len(number.as_tuple().digits) > 100
    ):
        raise ValueError("Financial fact exceeds supported decimal precision")
    text = format(number, "f")
    return text.rstrip("0").rstrip(".") if "." in text else text


def duration(fact):
    return (
        date.fromisoformat(fact["end"]) - date.fromisoformat(fact["start"])
    ).days + 1


def collect(bundle, filing, tags):
    facts = []
    for tag in tags:
        values = (
            bundle["companyfacts"]
            .get("facts", {})
            .get("us-gaap", {})
            .get(tag, {})
            .get("units", {})
            .get("USD", [])
        )
        for row in values:
            if (row.get("accn"), row.get("form"), row.get("filed")) != (
                filing["accessionNumber"],
                filing["form"],
                filing["filingDate"],
            ):
                continue
            end = date.fromisoformat(row["end"])
            start = date.fromisoformat(row["start"]) if row.get("start") else None
            if end > filing["filed"] or (start and start > end):
                raise ValueError("Invalid financial statement period")
            facts.append(
                dict(
                    concept=tag,
                    namespace="us-gaap",
                    value=decimal_text(row["val"]),
                    unit="USD",
                    start=start.isoformat() if start else None,
                    end=end.isoformat(),
                    accession=row["accn"],
                    form=row["form"],
                    filed=row["filed"],
                )
            )
    return facts


def unique(candidates, tags):
    scopes = {(f["start"], f["end"], f["value"]) for f in candidates}
    if len(scopes) > 1:
        return None, "Conflicting values or periods in the selected filing."
    if not candidates:
        return None, "No compatible whole-company USD fact in the selected filing."
    return (
        sorted(
            candidates,
            key=lambda f: (tags.index(f["concept"]), json.dumps(f, sort_keys=True)),
        )[0],
        None,
    )


def select(facts, filing, kind, group, tags):
    candidates = [f for f in facts if f["end"] == filing["end"].isoformat()]
    if group == "Balance sheet":
        candidates = [f for f in candidates if f["start"] is None]
    else:
        low, high = (350, 380) if kind == "annual" else (70, 110)
        if group == "Cash generation" and kind == "quarter":
            high = 310
        candidates = [
            f for f in candidates if f["start"] and low <= duration(f) <= high
        ]
        if candidates and group == "Cash generation":
            # Preserve the longest reported period ending at the filing end. In
            # a 10-Q that is ordinarily YTD. Never subtract prior filings.
            longest = max(duration(f) for f in candidates)
            candidates = [f for f in candidates if duration(f) == longest]
    return unique(candidates, tags)


def prior_fact(facts, current, tags):
    if current is None:
        return None
    if current["start"] is None:
        candidates = [
            f for f in facts if f["start"] is None and f["end"] < current["end"]
        ]
        if candidates:
            end = max(f["end"] for f in candidates)
            candidates = [f for f in candidates if f["end"] == end]
    else:
        candidates = [
            f
            for f in facts
            if f["start"]
            and 357
            <= (date.fromisoformat(current["end"]) - date.fromisoformat(f["end"])).days
            <= 373
            and abs(duration(f) - duration(current)) <= 7
        ]
    return unique(candidates, tags)[0]


def derived(key, label, group, inputs, formula, compute, unit, explanation):
    valid = all(f and f.get("value") is not None for f in inputs)
    reason = None
    value = None
    if not valid:
        reason = "A required compatible input is unavailable."
    elif len({(f["start"], f["end"]) for f in inputs}) != 1:
        reason = "Inputs cover different reporting periods."
    else:
        with localcontext() as ctx:
            ctx.prec = 28
            value, reason = compute(*[Decimal(f["value"]) for f in inputs])
    evidence = [f for f in inputs if f]
    return dict(
        key=key,
        label=label,
        group=group,
        value=decimal_text(value) if value is not None else None,
        unit=unit,
        start=evidence[0]["start"] if evidence else None,
        end=evidence[0]["end"] if evidence else None,
        inputs=evidence,
        prior=None,
        reason=reason,
        formula=formula,
        explanation=explanation,
        calculated=True,
    )


def normalize_performance(bundle, cik, now):
    for name in ("companyfacts", "submissions"):
        if str(bundle[name].get("cik")).lstrip("0") != str(cik):
            raise ValueError("SEC evidence belongs to another company")
    filings = filing_rows(bundle["submissions"], now)
    reports = {}
    for kind, form in (("annual", "10-K"), ("quarter", "10-Q")):
        matches = [f for f in filings if f["form"].startswith(form)]
        if not matches:
            reports[kind] = None
            continue
        filing = matches[-1]
        selected = {}
        metrics = []
        for key, (label, group, tags, explanation) in DEFINITIONS.items():
            facts = collect(bundle, filing, tags)
            fact, error = select(facts, filing, kind, group, tags)
            selected[key] = fact
            prior = prior_fact(facts, fact, tags)
            metrics.append(
                dict(
                    key=key,
                    label=label,
                    group=group,
                    value=fact["value"] if fact else None,
                    unit="USD",
                    start=fact["start"] if fact else None,
                    end=fact["end"] if fact else filing["end"].isoformat(),
                    inputs=[fact] if fact else [],
                    prior=prior,
                    reason=error,
                    formula=None,
                    explanation=explanation,
                    calculated=False,
                )
            )
        # Reuse the tested two-ratio selector against only this filing. This
        # cannot change the current monitoring source or any saved assessment.
        sub = dict(
            bundle["submissions"],
            filings={
                "recent": {
                    k: [filing[k]]
                    for k in (
                        "accessionNumber",
                        "filingDate",
                        "reportDate",
                        "form",
                        "primaryDocument",
                        "acceptanceDateTime",
                    )
                }
            },
        )
        normalized = normalize(bundle["companyfacts"], sub, cik, now)
        for calc in normalized["calculations"]:
            metrics.append(
                dict(
                    key=calc["metric"],
                    label=(
                        "Revenue growth vs prior year"
                        if calc["metric"] == "revenue_growth"
                        else "Operating margin"
                    ),
                    group="Business performance",
                    value=calc["value"],
                    unit="percent",
                    start=(
                        normalized["period_start"].isoformat()
                        if normalized["period_start"]
                        else None
                    ),
                    end=filing["end"].isoformat(),
                    inputs=calc["inputs"],
                    prior=None,
                    reason=calc["reason"],
                    formula=calc["formula"],
                    explanation="Calculated from the selected filing's compatible reported inputs.",
                    calculated=True,
                )
            )
        metrics.append(
            derived(
                "free_cash_flow",
                "Free cash flow (app calculation)",
                "Cash generation",
                [selected["operating_cash"], selected["capital_spending"]],
                "Operating cash flow − cash payments for property, plant and equipment",
                lambda cash, capex: (
                    (cash - capex, None)
                    if capex >= 0
                    else (
                        None,
                        "Capital spending is negative; this convention is not applied.",
                    )
                ),
                "USD",
                "Non-GAAP calculation; excludes noncash capital additions and is not cash available for discretionary spending. Other definitions can differ.",
            )
        )
        metrics.append(
            derived(
                "liabilities_assets",
                "Liabilities / assets",
                "Balance sheet",
                [selected["liabilities"], selected["assets"]],
                "Total liabilities / total assets × 100",
                lambda liabilities, assets: (
                    (liabilities / assets * 100, None)
                    if assets > 0
                    else (None, "Total assets must be positive.")
                ),
                "percent",
                "Share of assets represented by total liabilities. This is not a debt ratio or a credit rating.",
            )
        )
        reports[kind] = dict(
            period_type=kind,
            accession=filing["accessionNumber"],
            form=filing["form"],
            period_end=filing["end"].isoformat(),
            published_at=filing["accepted_at"].isoformat(),
            filed_on=filing["filed"].isoformat(),
            filing_url=normalized["filing_url"],
            metrics=metrics,
        )
    return dict(
        method=METHOD,
        reports=reports,
        limitations=[
            "Whole-company US-GAAP USD facts only; no custom tags, currency conversion or segment estimates.",
            "Annual and latest direct-quarter filings are selected separately; the latest 10-Q can be older than the annual report.",
            "Cash flow uses the longest compatible reported period in each selected filing, normally fiscal year to date for a 10-Q. It is not inferred quarterly cash flow.",
            "Debt components are displayed separately and are not added into a total. Missing components are unknown, not zero.",
            "Reported inputs and comparisons come from the same accession. Amendments without usable facts remain unavailable.",
        ],
    )


def persist(conn, iid, pid, bundle, cik, now):
    data = normalize_performance(bundle, cik, now)
    previous = one(
        conn,
        "SELECT p.data FROM performance_current c JOIN performance_snapshots p ON p.id=c.snapshot_id WHERE c.instrument_id=%s",
        (iid,),
    )
    if previous:
        for kind, old in previous["data"]["reports"].items():
            new = data["reports"][kind]
            if old and (
                not new
                or (new["period_end"], new["published_at"])
                < (old["period_end"], old["published_at"])
            ):
                raise ValueError(
                    "SEC response omits or predates a retained financial report; prior evidence is preserved"
                )
    digest = hashlib.sha256(
        json.dumps(data, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    sid = uuid5(NAMESPACE_URL, "thesis:performance:" + str(iid) + ":" + digest)
    conn.execute(
        "INSERT INTO performance_snapshots(id,instrument_id,payload_id,method,data,created_at) VALUES(%s,%s,%s,%s,%s,%s) ON CONFLICT DO NOTHING",
        (sid, iid, pid, METHOD, Jsonb(data), now),
    )
    conn.execute(
        "INSERT INTO performance_current VALUES(%s,%s,%s) ON CONFLICT(instrument_id) DO UPDATE SET snapshot_id=excluded.snapshot_id,checked_at=excluded.checked_at",
        (iid, sid, now),
    )
    return sid


def present(conn, iid, *, resolve_amendments=False):
    if not one(
        conn,
        "SELECT id FROM sources WHERE id='sec-companyfacts' AND entitlement='sec-public'",
    ):
        return dict(
            status="unavailable",
            reason="Structured filing source access is unavailable.",
            reports={},
        )
    record = one(
        conn,
        "SELECT p.id,p.payload_id,p.method,p.data,p.created_at,c.checked_at FROM performance_current c JOIN performance_snapshots p ON p.id=c.snapshot_id AND p.instrument_id=c.instrument_id WHERE c.instrument_id=%s",
        (iid,),
    )
    if not record:
        return dict(
            status="empty",
            reason="Refresh filings to prepare annual and quarterly financials.",
            reports={},
        )
    health = one(
        conn,
        "SELECT last_attempt_at,last_error FROM sec_refresh_state WHERE instrument_id=%s",
        (iid,),
    )
    result = dict(
        status="available",
        snapshot_id=record["id"],
        payload_id=record["payload_id"],
        first_recorded_at=record["created_at"],
        checked_at=record["checked_at"],
        source_status=health,
        **record["data"]
    )
    if resolve_amendments:
        from .amendments import present as resolved
        return resolved(conn, iid, result)
    return result
